### ISSUE TITLE
Error when multiplying weight matrix with state in forward function of Actor class

### ISSUE THREAD

**Issue by EudaimoniAya** [tuantran23012000/Recommendation-system#4]
I'm very sorry to bother you, but I'm having this problem below when I run the code:

      Traceback (most recent call last):
        File "C:/Users/31084/Desktop/Recommendation-system-main/main.py", line 31, in <module>
          action = agent.get_action(state)
        File "C:\Users\31084\Desktop\Recommendation-system-main\algorithm\ddpg.py", line 67, in get_action
          action = self.actor.forward(state)
        File "C:\Users\31084\Desktop\Recommendation-system-main\src\model.py", line 62, in forward
          state = self.weight_matrix.matmul(state)
      RuntimeError: size mismatch, m1: [576 x 20], m2: [3 x 1] at ..\aten\src\TH/generic/THTensorMath.cpp:41

In the forward function of the Actor class it will multiply 'self.weight_matrix' of shape (1, 3) with 'state' of shape (1, 20, 576). I'm trying to figure out how I should handle this to make sure the shape of the argument matches successfully.

**Comment by EudaimoniAya** [comment]
The problem has been resolved, the Actor network parameter "input_sequence_length" should be the length of the history state: "max_lag = 20"; the parameter "output_sequence_length" should be the length of the recommended list: "dim_action = 3".

**Comment by JingwenShizuka** [comment]
In addition, there is a problem in the MyEnv class where the user interaction data in the file "Data_Acc_Item.csv" is sorted in descending chronological order. In the MyEnv class, the function step() will output the status of an interaction record and the 19 interaction information of the user later than that record; the function get_observation() will output the status of 20 interaction information later than that of an interaction record.
In the implementation of the main function, the function get_observation() is used for the initialization of the state and the reselection of the interaction records in the inner loop, and the function step() is used to generate the new state after the Actor performs an action. Therefore the output of function step() should contain information about a much later interaction, and from the result: state and new_state seem to be reversed.
The problem can be solved if the chronological ordering of "Data_Acc_Item.csv" is changed to sequential or if the way get_observation() and step() generate state is swapped.
